export type ToolPlan = 'Free' | 'Pro' | 'Premium';

export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: string;
  plan: ToolPlan;
  featured?: boolean;
  popular?: boolean;
  keywords?: string[];
};

export const tools: Tool[] = [
  {
    slug: 'image-converter',
    name: 'Image Converter',
    description: 'Convert PNG, JPG, and WebP files in your browser.',
    category: 'Media',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['image', 'png', 'jpg', 'webp', 'converter'],
  },
  {
    slug: 'whatsapp-link',
    name: 'WhatsApp Link Generator',
    description: 'Build clean WhatsApp chat links with pre-filled messages.',
    category: 'Growth',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['whatsapp', 'marketing', 'link', 'message'],
  },
  {
    slug: 'invoice-maker',
    name: 'Invoice Maker',
    description: 'Create itemized invoices and export them as PDFs.',
    category: 'Business',
    plan: 'Pro',
    featured: true,
    popular: true,
    keywords: ['invoice', 'pdf', 'billing', 'business'],
  },
  {
    slug: 'expiring-link',
    name: 'Expiring Link Generator',
    description: 'Upload files and share links that expire automatically.',
    category: 'Files',
    plan: 'Pro',
    keywords: ['file', 'share', 'expiring', 'download'],
  },
  {
    slug: 'file-locker',
    name: 'File Locker',
    description: 'Protect uploads with passphrases and signed downloads.',
    category: 'Files',
    plan: 'Premium',
    featured: true,
    keywords: ['locker', 'secure', 'password', 'storage'],
  },
  {
    slug: 'voice-to-text',
    name: 'Voice to Text',
    description: 'Transcribe audio or video files with AssemblyAI.',
    category: 'AI',
    plan: 'Premium',
    keywords: ['audio', 'transcription', 'voice', 'ai'],
  },
  {
    slug: 'image-to-text',
    name: 'Image to Text',
    description: 'Extract text from images with OCR.',
    category: 'AI',
    plan: 'Free',
    popular: true,
    keywords: ['ocr', 'text', 'image', 'ai'],
  },
  {
    slug: 'stamp-signature',
    name: 'Stamp and Signature',
    description: 'Draw signatures and generate stamp PNGs.',
    category: 'Documents',
    plan: 'Free',
    keywords: ['signature', 'stamp', 'png', 'documents'],
  },
  {
    slug: 'send-later',
    name: 'Send Later',
    description: 'Schedule emails for later delivery.',
    category: 'Productivity',
    plan: 'Pro',
    keywords: ['email', 'schedule', 'send later'],
  },
  {
    slug: 'cv-maker',
    name: 'CV Maker',
    description: 'Create a polished resume and download it as PDF.',
    category: 'Documents',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['resume', 'cv', 'pdf', 'career'],
  },
  {
    slug: 'video-converter',
    name: 'Video Converter',
    description: 'Convert videos to MP4 or WebM in the browser.',
    category: 'Media',
    plan: 'Premium',
    featured: true,
    keywords: ['video', 'mp4', 'webm', 'converter'],
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create QR codes for links, WhatsApp messages, and text.',
    category: 'Growth',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['qr', 'code', 'url', 'whatsapp'],
  },
  {
    slug: 'pdf-tools',
    name: 'PDF Tools',
    description: 'Convert images to PDF and prepare PDF workflows.',
    category: 'Documents',
    plan: 'Free',
    keywords: ['pdf', 'image', 'merge', 'compress'],
  },
  {
    slug: 'calculators',
    name: 'Calculators',
    description: 'Quick percentage, currency-style, and freelance calculators.',
    category: 'Productivity',
    plan: 'Free',
    popular: true,
    keywords: ['calculator', 'percentage', 'currency', 'freelance'],
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and reading time.',
    category: 'Text',
    plan: 'Free',
    popular: true,
    keywords: ['word', 'counter', 'text', 'reading time'],
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Check characters, letters, numbers, spaces, and line counts.',
    category: 'Text',
    plan: 'Free',
    keywords: ['character', 'counter', 'letters', 'text'],
  },
  {
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text to uppercase, lowercase, title case, and more.',
    category: 'Text',
    plan: 'Free',
    popular: true,
    keywords: ['case', 'uppercase', 'lowercase', 'title case'],
  },
  {
    slug: 'remove-extra-spaces',
    name: 'Remove Extra Spaces',
    description: 'Clean whitespace, blank lines, and messy pasted text.',
    category: 'Text',
    plan: 'Free',
    keywords: ['spaces', 'cleanup', 'whitespace', 'text'],
  },
  {
    slug: 'duplicate-line-remover',
    name: 'Duplicate Line Remover',
    description: 'Remove repeated lines while keeping your text order.',
    category: 'Text',
    plan: 'Free',
    keywords: ['duplicate', 'lines', 'remove', 'text'],
  },
  {
    slug: 'text-sorter',
    name: 'Text Sorter',
    description: 'Sort lines alphabetically, reverse them, or deduplicate lists.',
    category: 'Text',
    plan: 'Free',
    keywords: ['sort', 'lines', 'alphabetical', 'list'],
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Create clean URL slugs from titles and headings.',
    category: 'Text',
    plan: 'Free',
    popular: true,
    keywords: ['slug', 'url', 'seo', 'title'],
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, minify, and validate JSON in your browser.',
    category: 'Developer',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['json', 'formatter', 'validator', 'developer'],
  },
  {
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder Decoder',
    description: 'Encode or decode Base64 strings instantly.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['base64', 'encode', 'decode'],
  },
  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder Decoder',
    description: 'Encode and decode URL query strings safely.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['url', 'encode', 'decode', 'query'],
  },
  {
    slug: 'html-entity-encoder-decoder',
    name: 'HTML Entity Encoder Decoder',
    description: 'Escape and unescape HTML entities for safe snippets.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['html', 'entities', 'escape', 'decode'],
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions against sample text.',
    category: 'Developer',
    plan: 'Free',
    popular: true,
    keywords: ['regex', 'regular expression', 'match', 'developer'],
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT headers and payloads without sending data away.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['jwt', 'token', 'decode', 'developer'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID values for tests, records, and prototypes.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['uuid', 'guid', 'generator'],
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA hashes from text in your browser.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['hash', 'sha', 'checksum', 'developer'],
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO title, description, canonical, and social tags.',
    category: 'SEO',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['meta tags', 'seo', 'title', 'description'],
  },
  {
    slug: 'open-graph-preview',
    name: 'Open Graph Preview',
    description: 'Preview how a page card can look on social platforms.',
    category: 'SEO',
    plan: 'Free',
    keywords: ['open graph', 'og', 'preview', 'social'],
  },
  {
    slug: 'keyword-density-checker',
    name: 'Keyword Density Checker',
    description: 'Find repeated terms and keyword density in page copy.',
    category: 'SEO',
    plan: 'Free',
    popular: true,
    keywords: ['keyword', 'density', 'seo', 'content'],
  },
  {
    slug: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    description: 'Create a clean robots.txt file with sitemap support.',
    category: 'SEO',
    plan: 'Free',
    keywords: ['robots.txt', 'crawler', 'seo', 'sitemap'],
  },
  {
    slug: 'sitemap-xml-generator',
    name: 'Sitemap XML Generator',
    description: 'Generate a simple XML sitemap from a list of URLs.',
    category: 'SEO',
    plan: 'Free',
    keywords: ['sitemap', 'xml', 'seo', 'urls'],
  },
  {
    slug: 'schema-markup-generator',
    name: 'Schema Markup Generator',
    description: 'Generate basic JSON-LD schema for websites and businesses.',
    category: 'SEO',
    plan: 'Free',
    keywords: ['schema', 'json-ld', 'seo', 'structured data'],
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images with quality controls before download.',
    category: 'Media',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['image', 'compress', 'jpeg', 'quality'],
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images by width and height in the browser.',
    category: 'Media',
    plan: 'Free',
    popular: true,
    keywords: ['image', 'resize', 'dimensions', 'canvas'],
  },
  {
    slug: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors and copy HEX, RGB, and HSL values.',
    category: 'Design',
    plan: 'Free',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'design'],
  },
  {
    slug: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Build CSS linear gradients with live previews.',
    category: 'Design',
    plan: 'Free',
    popular: true,
    keywords: ['gradient', 'css', 'design', 'color'],
  },
  {
    slug: 'css-box-shadow-generator',
    name: 'CSS Box Shadow Generator',
    description: 'Design and copy CSS box-shadow values visually.',
    category: 'Design',
    plan: 'Free',
    keywords: ['box shadow', 'css', 'design', 'generator'],
  },
  {
    slug: 'profit-margin-calculator',
    name: 'Profit Margin Calculator',
    description: 'Calculate cost, revenue, profit, markup, and margin.',
    category: 'Business',
    plan: 'Free',
    keywords: ['profit', 'margin', 'markup', 'business'],
  },
  {
    slug: 'gst-tax-calculator',
    name: 'GST Tax Calculator',
    description: 'Add or remove GST and sales tax from an amount.',
    category: 'Business',
    plan: 'Free',
    keywords: ['gst', 'tax', 'sales tax', 'calculator'],
  },
  {
    slug: 'loan-emi-calculator',
    name: 'Loan EMI Calculator',
    description: 'Estimate monthly payments, total interest, and payoff totals.',
    category: 'Business',
    plan: 'Free',
    popular: true,
    keywords: ['loan', 'emi', 'payment', 'interest'],
  },
  {
    slug: 'paypal-stripe-fee-calculator',
    name: 'PayPal Stripe Fee Calculator',
    description: 'Estimate payment processor fees and required charge amounts.',
    category: 'Business',
    plan: 'Free',
    keywords: ['paypal', 'stripe', 'fee', 'freelance'],
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    description: 'Calculate sale price, discount value, and savings.',
    category: 'Business',
    plan: 'Free',
    keywords: ['discount', 'sale', 'price', 'calculator'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong passwords with length and character controls.',
    category: 'Productivity',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['password', 'security', 'generator'],
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate age in years, months, and days from a birth date.',
    category: 'Productivity',
    plan: 'Free',
    keywords: ['age', 'birthday', 'date', 'calculator'],
  },
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert common length, weight, and temperature units.',
    category: 'Productivity',
    plan: 'Free',
    keywords: ['unit', 'converter', 'length', 'weight', 'temperature'],
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to readable dates and back.',
    category: 'Productivity',
    plan: 'Free',
    keywords: ['timestamp', 'unix', 'date', 'converter'],
  },
];

export function toolHref(slug: string) {
  return `/tools/${slug}`;
}

const trafficTools: Tool[] = [
  { slug: 'keyword-research-tool', name: 'Keyword Research Tool', description: 'Generate keyword ideas, intent clusters, and content angles.', category: 'SEO', plan: 'Free', popular: true, keywords: ['keyword research', 'seo', 'content ideas'] },
  { slug: 'ai-meta-title-description-generator', name: 'AI Meta Title & Description Generator', description: 'Draft SEO titles and meta descriptions from a topic or URL.', category: 'SEO', plan: 'Free', featured: true, keywords: ['ai meta title', 'meta description', 'seo'] },
  { slug: 'seo-score-checker', name: 'SEO Score Checker', description: 'Score page copy for title, description, headings, links, and keyword use.', category: 'SEO', plan: 'Free', popular: true, keywords: ['seo score', 'seo checker', 'audit'] },
  { slug: 'website-audit-tool', name: 'Website Audit Tool', description: 'Create a practical website audit checklist and priority report.', category: 'SEO', plan: 'Free', keywords: ['website audit', 'seo audit', 'technical seo'] },
  { slug: 'backlink-checker', name: 'Backlink Checker', description: 'Prepare backlink audit notes and outreach tracking fields.', category: 'SEO', plan: 'Premium', keywords: ['backlink', 'link building', 'seo'] },
  { slug: 'google-index-checker', name: 'Google Index Checker', description: 'Generate index-check commands and URL inspection notes.', category: 'SEO', plan: 'Free', keywords: ['google index', 'indexed pages', 'seo'] },
  { slug: 'broken-link-checker', name: 'Broken Link Checker', description: 'Paste URLs and build a broken-link testing checklist.', category: 'SEO', plan: 'Free', keywords: ['broken links', '404', 'links'] },
  { slug: 'page-speed-analyzer', name: 'Page Speed Analyzer', description: 'Create a performance audit checklist for Core Web Vitals fixes.', category: 'SEO', plan: 'Free', popular: true, keywords: ['page speed', 'performance', 'core web vitals'] },
  { slug: 'serp-preview-tool', name: 'SERP Preview Tool', description: 'Preview how a title, URL, and description can appear in search.', category: 'SEO', plan: 'Free', keywords: ['serp preview', 'google snippet', 'seo'] },
  { slug: 'ai-blog-outline-generator', name: 'AI Blog Outline Generator', description: 'Generate blog outlines, headings, FAQs, and search intent notes.', category: 'SEO', plan: 'Free', popular: true, keywords: ['blog outline', 'ai writing', 'seo content'] },
  { slug: 'plagiarism-checker', name: 'Plagiarism Checker', description: 'Compare pasted texts and estimate similarity signals.', category: 'Content', plan: 'Free', keywords: ['plagiarism', 'similarity', 'content'] },
  { slug: 'domain-authority-checker', name: 'Domain Authority Checker', description: 'Create a domain authority research checklist and scoring sheet.', category: 'SEO', plan: 'Premium', keywords: ['domain authority', 'seo', 'domain'] },
  { slug: 'xml-sitemap-validator', name: 'XML Sitemap Validator', description: 'Validate XML sitemap structure and URL entries.', category: 'SEO', plan: 'Free', keywords: ['xml sitemap', 'validator', 'seo'] },
  { slug: 'html-css-js-minifier', name: 'HTML/CSS/JS Minifier', description: 'Minify frontend snippets for quick experiments.', category: 'Developer', plan: 'Free', popular: true, keywords: ['minifier', 'html', 'css', 'javascript'] },
  { slug: 'sql-formatter', name: 'SQL Formatter', description: 'Format SQL queries into readable multi-line statements.', category: 'Developer', plan: 'Free', keywords: ['sql formatter', 'database', 'query'] },
  { slug: 'api-tester', name: 'API Tester', description: 'Build fetch snippets for lightweight API request testing.', category: 'Developer', plan: 'Free', featured: true, keywords: ['api tester', 'postman', 'fetch'] },
  { slug: 'cron-expression-generator', name: 'Cron Expression Generator', description: 'Generate common cron schedules and explain them.', category: 'Developer', plan: 'Free', keywords: ['cron', 'schedule', 'developer'] },
  { slug: 'git-cheat-generator', name: 'Git Cheat Generator', description: 'Generate Git commands for common version-control tasks.', category: 'Developer', plan: 'Free', keywords: ['git', 'cheat sheet', 'commands'] },
  { slug: 'curl-converter', name: 'cURL Converter', description: 'Convert simple cURL commands into fetch snippets.', category: 'Developer', plan: 'Free', keywords: ['curl', 'fetch', 'api'] },
  { slug: 'lorem-ipsum-generator', name: 'Lorem Ipsum Generator', description: 'Generate placeholder paragraphs for layouts and mockups.', category: 'Developer', plan: 'Free', keywords: ['lorem ipsum', 'placeholder', 'text'] },
  { slug: 'code-screenshot-generator', name: 'Code Screenshot Generator', description: 'Create a polished code-card preview for screenshots.', category: 'Developer', plan: 'Free', keywords: ['code screenshot', 'developer', 'image'] },
  { slug: 'image-to-base64', name: 'Image to Base64', description: 'Convert image files into Base64 data URLs.', category: 'Developer', plan: 'Free', keywords: ['image base64', 'data url', 'encode'] },
  { slug: 'env-file-generator', name: 'ENV File Generator', description: 'Generate clean .env templates from key-value rows.', category: 'Developer', plan: 'Free', keywords: ['env', 'environment variables', 'developer'] },
  { slug: 'docker-command-generator', name: 'Docker Command Generator', description: 'Generate Docker run and compose starter commands.', category: 'Developer', plan: 'Free', keywords: ['docker', 'command', 'compose'] },
  { slug: 'markdown-previewer', name: 'Markdown Previewer', description: 'Preview markdown structure and plain rendered content.', category: 'Developer', plan: 'Free', popular: true, keywords: ['markdown', 'preview', 'developer'] },
  { slug: 'online-code-editor', name: 'Online Code Editor', description: 'Draft HTML, CSS, and JavaScript snippets in one place.', category: 'Developer', plan: 'Free', keywords: ['code editor', 'html', 'css', 'javascript'] },
  { slug: 'ai-code-explainer', name: 'AI Code Explainer', description: 'Generate plain-English explanations for pasted code.', category: 'AI', plan: 'Free', keywords: ['code explainer', 'ai', 'developer'] },
  { slug: 'background-remover', name: 'Background Remover', description: 'Prepare image background removal instructions and preview workflow.', category: 'Design', plan: 'Premium', popular: true, keywords: ['background remover', 'image', 'design'] },
  { slug: 'svg-optimizer', name: 'SVG Optimizer', description: 'Clean SVG markup and remove common unnecessary whitespace.', category: 'Design', plan: 'Free', keywords: ['svg optimizer', 'svg', 'design'] },
  { slug: 'color-palette-generator', name: 'Color Palette Generator', description: 'Generate brand color palettes from a base color.', category: 'Design', plan: 'Free', popular: true, keywords: ['color palette', 'design', 'branding'] },
  { slug: 'glassmorphism-generator', name: 'Glassmorphism Generator', description: 'Generate CSS glass panels with live values.', category: 'Design', plan: 'Free', keywords: ['glassmorphism', 'css', 'design'] },
  { slug: 'neumorphism-generator', name: 'Neumorphism Generator', description: 'Generate soft UI shadow styles for components.', category: 'Design', plan: 'Free', keywords: ['neumorphism', 'css', 'design'] },
  { slug: 'font-pairing-tool', name: 'Font Pairing Tool', description: 'Suggest practical font pairings for web layouts.', category: 'Design', plan: 'Free', keywords: ['font pairing', 'typography', 'design'] },
  { slug: 'ai-logo-generator', name: 'AI Logo Generator', description: 'Generate logo concept prompts, colors, and layout directions.', category: 'Design', plan: 'Premium', popular: true, keywords: ['ai logo', 'logo maker', 'branding'] },
  { slug: 'banner-thumbnail-maker', name: 'Banner/Thumbnail Maker', description: 'Draft banner and thumbnail layouts with copy blocks.', category: 'Design', plan: 'Free', keywords: ['banner', 'thumbnail', 'design'] },
  { slug: 'social-media-post-resizer', name: 'Social Media Post Resizer', description: 'Pick platform sizes for posts, stories, covers, and thumbnails.', category: 'Design', plan: 'Free', keywords: ['social media resizer', 'image size', 'design'] },
  { slug: 'favicon-generator', name: 'Favicon Generator', description: 'Generate favicon specs and simple SVG favicon markup.', category: 'Design', plan: 'Free', keywords: ['favicon', 'icon', 'website'] },
  { slug: 'mockup-generator', name: 'Mockup Generator', description: 'Generate product mockup layout notes and image prompts.', category: 'Design', plan: 'Premium', keywords: ['mockup', 'design', 'product'] },
  { slug: 'screenshot-beautifier', name: 'Screenshot Beautifier', description: 'Create CSS-style frames and notes for prettier screenshots.', category: 'Design', plan: 'Free', keywords: ['screenshot', 'beautifier', 'design'] },
  { slug: 'image-upscaler', name: 'Image Upscaler', description: 'Prepare upscale settings and export-size planning for images.', category: 'Design', plan: 'Premium', keywords: ['image upscaler', 'image', 'ai'] },
  { slug: 'watermark-tool', name: 'Watermark Tool', description: 'Add text watermark guidance and placement settings for assets.', category: 'Design', plan: 'Free', keywords: ['watermark', 'image', 'brand'] },
  { slug: 'ai-icon-generator', name: 'AI Icon Generator', description: 'Generate icon prompts, style rules, and SVG starter shapes.', category: 'Design', plan: 'Premium', keywords: ['ai icon', 'icon generator', 'design'] },
  { slug: 'svg-blob-generator', name: 'SVG Blob Generator', description: 'Generate organic SVG blob shapes for backgrounds.', category: 'Design', plan: 'Free', keywords: ['svg blob', 'blob generator', 'design'] },
  { slug: 'css-animation-generator', name: 'CSS Animation Generator', description: 'Generate keyframes for fades, slides, pulses, and loops.', category: 'Design', plan: 'Free', keywords: ['css animation', 'keyframes', 'design'] },
  { slug: 'ai-article-writer', name: 'AI Article Writer', description: 'Generate article drafts from a topic, audience, and tone.', category: 'Content', plan: 'Premium', featured: true, keywords: ['ai article writer', 'content', 'blog'] },
  { slug: 'ai-paraphrasing-tool', name: 'AI Paraphrasing Tool', description: 'Rewrite text in clearer, shorter, or more professional styles.', category: 'Content', plan: 'Free', popular: true, keywords: ['paraphrase', 'rewrite', 'ai'] },
  { slug: 'ai-grammar-checker', name: 'AI Grammar Checker', description: 'Find grammar issues and produce a cleaner version.', category: 'Content', plan: 'Free', keywords: ['grammar checker', 'writing', 'ai'] },
  { slug: 'ai-email-writer', name: 'AI Email Writer', description: 'Generate professional emails from short instructions.', category: 'Content', plan: 'Free', keywords: ['email writer', 'ai', 'business'] },
  { slug: 'ai-upwork-proposal-generator', name: 'AI Upwork Proposal Generator', description: 'Draft freelance proposals for client job posts.', category: 'Content', plan: 'Free', popular: true, keywords: ['upwork proposal', 'freelance', 'ai'] },
  { slug: 'ai-fiverr-gig-generator', name: 'AI Fiverr Gig Generator', description: 'Generate Fiverr gig titles, packages, FAQs, and descriptions.', category: 'Content', plan: 'Free', keywords: ['fiverr gig', 'freelance', 'ai'] },
  { slug: 'ai-product-description-generator', name: 'AI Product Description Generator', description: 'Draft ecommerce product descriptions and benefits.', category: 'Content', plan: 'Free', keywords: ['product description', 'ecommerce', 'ai'] },
  { slug: 'ai-hashtag-generator', name: 'AI Hashtag Generator', description: 'Generate hashtags grouped by topic and platform.', category: 'Content', plan: 'Free', keywords: ['hashtag generator', 'social media', 'ai'] },
  { slug: 'ai-resume-builder', name: 'AI Resume Builder', description: 'Generate resume bullets, summaries, and role-specific wording.', category: 'Content', plan: 'Free', keywords: ['resume builder', 'cv', 'ai'] },
  { slug: 'ai-cover-letter-generator', name: 'AI Cover Letter Generator', description: 'Draft cover letters for specific roles and companies.', category: 'Content', plan: 'Free', keywords: ['cover letter', 'job', 'ai'] },
  { slug: 'ai-chatbot-assistant', name: 'AI Chatbot Assistant', description: 'Create chatbot scripts, intents, and reply flows.', category: 'AI', plan: 'Premium', keywords: ['chatbot', 'assistant', 'ai'] },
  { slug: 'ai-translation-tool', name: 'AI Translation Tool', description: 'Prepare translation drafts and localization notes.', category: 'Content', plan: 'Free', keywords: ['translation', 'language', 'ai'] },
  { slug: 'quotation-generator', name: 'Quotation Generator', description: 'Create professional quotations for services and products.', category: 'Business', plan: 'Free', keywords: ['quotation', 'estimate', 'business'] },
  { slug: 'time-tracker', name: 'Time Tracker', description: 'Track session time and calculate billable totals.', category: 'Business', plan: 'Free', keywords: ['time tracker', 'freelance', 'billable'] },
  { slug: 'freelancer-contract-generator', name: 'Freelancer Contract Generator', description: 'Generate simple freelance contract clauses and scope notes.', category: 'Business', plan: 'Pro', keywords: ['contract', 'freelance', 'client'] },
  { slug: 'receipt-generator', name: 'Receipt Generator', description: 'Generate receipt text for payments and client records.', category: 'Business', plan: 'Free', keywords: ['receipt', 'payment', 'business'] },
  { slug: 'currency-converter', name: 'Currency Converter', description: 'Convert amounts with a manual exchange rate.', category: 'Business', plan: 'Free', keywords: ['currency converter', 'exchange rate', 'money'] },
  { slug: 'online-notepad-sync', name: 'Online Notepad Sync', description: 'Draft notes locally with export-ready formatting.', category: 'Productivity', plan: 'Free', keywords: ['notepad', 'notes', 'sync'] },
  { slug: 'subscription-calculator', name: 'Subscription Calculator', description: 'Calculate monthly, annual, and lifetime subscription value.', category: 'Business', plan: 'Free', keywords: ['subscription', 'pricing', 'calculator'] },
  { slug: 'url-shortener', name: 'URL Shortener', description: 'Generate short-link slugs and campaign URL ideas.', category: 'Growth', plan: 'Pro', popular: true, keywords: ['url shortener', 'short link', 'growth'] },
  { slug: 'meme-generator', name: 'Meme Generator', description: 'Create meme text layouts and caption ideas.', category: 'Growth', plan: 'Free', popular: true, keywords: ['meme', 'caption', 'viral'] },
  { slug: 'screenshot-to-code-ai', name: 'Screenshot to Code AI', description: 'Generate implementation notes from screenshot descriptions.', category: 'AI', plan: 'Premium', popular: true, keywords: ['screenshot to code', 'ai', 'frontend'] },
  { slug: 'text-to-speech', name: 'Text to Speech', description: 'Prepare scripts and browser speech playback for text.', category: 'AI', plan: 'Free', popular: true, keywords: ['text to speech', 'tts', 'voice'] },
];

const existingSlugs = new Set(tools.map((tool) => tool.slug));
tools.push(...trafficTools.filter((tool) => !existingSlugs.has(tool.slug)));
