export type ToolPlan = 'Free' | 'Pro' | 'Premium';

export type Tool = {
  slug: string;
  name: string;
  description: string;
  category: string;
  plan: ToolPlan;
  featured?: boolean;
  popular?: boolean;
  keywords?: string[];
};

export const tools: Tool[] = [
  {
    slug: 'image-converter',
    name: 'Image Converter',
    description: 'Convert PNG, JPG, and WebP files in your browser.',
    category: 'Media',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['image', 'png', 'jpg', 'webp', 'converter'],
  },
  {
    slug: 'whatsapp-link',
    name: 'WhatsApp Link Generator',
    description: 'Build clean WhatsApp chat links with pre-filled messages.',
    category: 'Growth',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['whatsapp', 'marketing', 'link', 'message'],
  },
  {
    slug: 'invoice-maker',
    name: 'Invoice Maker',
    description: 'Create itemized invoices and export them as PDFs.',
    category: 'Business',
    plan: 'Pro',
    featured: true,
    popular: true,
    keywords: ['invoice', 'pdf', 'billing', 'business'],
  },
  {
    slug: 'expiring-link',
    name: 'Expiring Link Generator',
    description: 'Upload files and share links that expire automatically.',
    category: 'Files',
    plan: 'Pro',
    keywords: ['file', 'share', 'expiring', 'download'],
  },
  {
    slug: 'file-locker',
    name: 'File Locker',
    description: 'Protect uploads with passphrases and signed downloads.',
    category: 'Files',
    plan: 'Premium',
    featured: true,
    keywords: ['locker', 'secure', 'password', 'storage'],
  },
  {
    slug: 'voice-to-text',
    name: 'Voice to Text',
    description: 'Transcribe audio or video files with AssemblyAI.',
    category: 'AI',
    plan: 'Premium',
    keywords: ['audio', 'transcription', 'voice', 'ai'],
  },
  {
    slug: 'image-to-text',
    name: 'Image to Text',
    description: 'Extract text from images with OCR.',
    category: 'AI',
    plan: 'Free',
    popular: true,
    keywords: ['ocr', 'text', 'image', 'ai'],
  },
  {
    slug: 'stamp-signature',
    name: 'Stamp and Signature',
    description: 'Draw signatures and generate stamp PNGs.',
    category: 'Documents',
    plan: 'Free',
    keywords: ['signature', 'stamp', 'png', 'documents'],
  },
  {
    slug: 'send-later',
    name: 'Send Later',
    description: 'Schedule emails for later delivery.',
    category: 'Productivity',
    plan: 'Pro',
    keywords: ['email', 'schedule', 'send later'],
  },
  {
    slug: 'cv-maker',
    name: 'CV Maker',
    description: 'Create a polished resume and download it as PDF.',
    category: 'Documents',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['resume', 'cv', 'pdf', 'career'],
  },
  {
    slug: 'video-converter',
    name: 'Video Converter',
    description: 'Convert videos to MP4 or WebM in the browser.',
    category: 'Media',
    plan: 'Premium',
    featured: true,
    keywords: ['video', 'mp4', 'webm', 'converter'],
  },
  {
    slug: 'qr-generator',
    name: 'QR Code Generator',
    description: 'Create QR codes for links, WhatsApp messages, and text.',
    category: 'Growth',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['qr', 'code', 'url', 'whatsapp'],
  },
  {
    slug: 'pdf-tools',
    name: 'PDF Tools',
    description: 'Convert images to PDF and prepare PDF workflows.',
    category: 'Documents',
    plan: 'Free',
    keywords: ['pdf', 'image', 'merge', 'compress'],
  },
  {
    slug: 'calculators',
    name: 'Calculators',
    description: 'Quick percentage, currency-style, and freelance calculators.',
    category: 'Productivity',
    plan: 'Free',
    popular: true,
    keywords: ['calculator', 'percentage', 'currency', 'freelance'],
  },
  {
    slug: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, sentences, and reading time.',
    category: 'Text',
    plan: 'Free',
    popular: true,
    keywords: ['word', 'counter', 'text', 'reading time'],
  },
  {
    slug: 'character-counter',
    name: 'Character Counter',
    description: 'Check characters, letters, numbers, spaces, and line counts.',
    category: 'Text',
    plan: 'Free',
    keywords: ['character', 'counter', 'letters', 'text'],
  },
  {
    slug: 'text-case-converter',
    name: 'Text Case Converter',
    description: 'Convert text to uppercase, lowercase, title case, and more.',
    category: 'Text',
    plan: 'Free',
    popular: true,
    keywords: ['case', 'uppercase', 'lowercase', 'title case'],
  },
  {
    slug: 'remove-extra-spaces',
    name: 'Remove Extra Spaces',
    description: 'Clean whitespace, blank lines, and messy pasted text.',
    category: 'Text',
    plan: 'Free',
    keywords: ['spaces', 'cleanup', 'whitespace', 'text'],
  },
  {
    slug: 'duplicate-line-remover',
    name: 'Duplicate Line Remover',
    description: 'Remove repeated lines while keeping your text order.',
    category: 'Text',
    plan: 'Free',
    keywords: ['duplicate', 'lines', 'remove', 'text'],
  },
  {
    slug: 'text-sorter',
    name: 'Text Sorter',
    description: 'Sort lines alphabetically, reverse them, or deduplicate lists.',
    category: 'Text',
    plan: 'Free',
    keywords: ['sort', 'lines', 'alphabetical', 'list'],
  },
  {
    slug: 'slug-generator',
    name: 'Slug Generator',
    description: 'Create clean URL slugs from titles and headings.',
    category: 'Text',
    plan: 'Free',
    popular: true,
    keywords: ['slug', 'url', 'seo', 'title'],
  },
  {
    slug: 'json-formatter',
    name: 'JSON Formatter',
    description: 'Format, minify, and validate JSON in your browser.',
    category: 'Developer',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['json', 'formatter', 'validator', 'developer'],
  },
  {
    slug: 'base64-encoder-decoder',
    name: 'Base64 Encoder Decoder',
    description: 'Encode or decode Base64 strings instantly.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['base64', 'encode', 'decode'],
  },
  {
    slug: 'url-encoder-decoder',
    name: 'URL Encoder Decoder',
    description: 'Encode and decode URL query strings safely.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['url', 'encode', 'decode', 'query'],
  },
  {
    slug: 'html-entity-encoder-decoder',
    name: 'HTML Entity Encoder Decoder',
    description: 'Escape and unescape HTML entities for safe snippets.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['html', 'entities', 'escape', 'decode'],
  },
  {
    slug: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test regular expressions against sample text.',
    category: 'Developer',
    plan: 'Free',
    popular: true,
    keywords: ['regex', 'regular expression', 'match', 'developer'],
  },
  {
    slug: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode JWT headers and payloads without sending data away.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['jwt', 'token', 'decode', 'developer'],
  },
  {
    slug: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID values for tests, records, and prototypes.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['uuid', 'guid', 'generator'],
  },
  {
    slug: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate SHA hashes from text in your browser.',
    category: 'Developer',
    plan: 'Free',
    keywords: ['hash', 'sha', 'checksum', 'developer'],
  },
  {
    slug: 'meta-tag-generator',
    name: 'Meta Tag Generator',
    description: 'Generate SEO title, description, canonical, and social tags.',
    category: 'SEO',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['meta tags', 'seo', 'title', 'description'],
  },
  {
    slug: 'open-graph-preview',
    name: 'Open Graph Preview',
    description: 'Preview how a page card can look on social platforms.',
    category: 'SEO',
    plan: 'Free',
    keywords: ['open graph', 'og', 'preview', 'social'],
  },
  {
    slug: 'keyword-density-checker',
    name: 'Keyword Density Checker',
    description: 'Find repeated terms and keyword density in page copy.',
    category: 'SEO',
    plan: 'Free',
    popular: true,
    keywords: ['keyword', 'density', 'seo', 'content'],
  },
  {
    slug: 'robots-txt-generator',
    name: 'Robots.txt Generator',
    description: 'Create a clean robots.txt file with sitemap support.',
    category: 'SEO',
    plan: 'Free',
    keywords: ['robots.txt', 'crawler', 'seo', 'sitemap'],
  },
  {
    slug: 'sitemap-xml-generator',
    name: 'Sitemap XML Generator',
    description: 'Generate a simple XML sitemap from a list of URLs.',
    category: 'SEO',
    plan: 'Free',
    keywords: ['sitemap', 'xml', 'seo', 'urls'],
  },
  {
    slug: 'schema-markup-generator',
    name: 'Schema Markup Generator',
    description: 'Generate basic JSON-LD schema for websites and businesses.',
    category: 'SEO',
    plan: 'Free',
    keywords: ['schema', 'json-ld', 'seo', 'structured data'],
  },
  {
    slug: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress images with quality controls before download.',
    category: 'Media',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['image', 'compress', 'jpeg', 'quality'],
  },
  {
    slug: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images by width and height in the browser.',
    category: 'Media',
    plan: 'Free',
    popular: true,
    keywords: ['image', 'resize', 'dimensions', 'canvas'],
  },
  {
    slug: 'color-picker',
    name: 'Color Picker',
    description: 'Pick colors and copy HEX, RGB, and HSL values.',
    category: 'Design',
    plan: 'Free',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'design'],
  },
  {
    slug: 'gradient-generator',
    name: 'Gradient Generator',
    description: 'Build CSS linear gradients with live previews.',
    category: 'Design',
    plan: 'Free',
    popular: true,
    keywords: ['gradient', 'css', 'design', 'color'],
  },
  {
    slug: 'css-box-shadow-generator',
    name: 'CSS Box Shadow Generator',
    description: 'Design and copy CSS box-shadow values visually.',
    category: 'Design',
    plan: 'Free',
    keywords: ['box shadow', 'css', 'design', 'generator'],
  },
  {
    slug: 'profit-margin-calculator',
    name: 'Profit Margin Calculator',
    description: 'Calculate cost, revenue, profit, markup, and margin.',
    category: 'Business',
    plan: 'Free',
    keywords: ['profit', 'margin', 'markup', 'business'],
  },
  {
    slug: 'gst-tax-calculator',
    name: 'GST Tax Calculator',
    description: 'Add or remove GST and sales tax from an amount.',
    category: 'Business',
    plan: 'Free',
    keywords: ['gst', 'tax', 'sales tax', 'calculator'],
  },
  {
    slug: 'loan-emi-calculator',
    name: 'Loan EMI Calculator',
    description: 'Estimate monthly payments, total interest, and payoff totals.',
    category: 'Business',
    plan: 'Free',
    popular: true,
    keywords: ['loan', 'emi', 'payment', 'interest'],
  },
  {
    slug: 'paypal-stripe-fee-calculator',
    name: 'PayPal Stripe Fee Calculator',
    description: 'Estimate payment processor fees and required charge amounts.',
    category: 'Business',
    plan: 'Free',
    keywords: ['paypal', 'stripe', 'fee', 'freelance'],
  },
  {
    slug: 'discount-calculator',
    name: 'Discount Calculator',
    description: 'Calculate sale price, discount value, and savings.',
    category: 'Business',
    plan: 'Free',
    keywords: ['discount', 'sale', 'price', 'calculator'],
  },
  {
    slug: 'password-generator',
    name: 'Password Generator',
    description: 'Generate strong passwords with length and character controls.',
    category: 'Productivity',
    plan: 'Free',
    featured: true,
    popular: true,
    keywords: ['password', 'security', 'generator'],
  },
  {
    slug: 'age-calculator',
    name: 'Age Calculator',
    description: 'Calculate age in years, months, and days from a birth date.',
    category: 'Productivity',
    plan: 'Free',
    keywords: ['age', 'birthday', 'date', 'calculator'],
  },
  {
    slug: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert common length, weight, and temperature units.',
    category: 'Productivity',
    plan: 'Free',
    keywords: ['unit', 'converter', 'length', 'weight', 'temperature'],
  },
  {
    slug: 'timestamp-converter',
    name: 'Timestamp Converter',
    description: 'Convert Unix timestamps to readable dates and back.',
    category: 'Productivity',
    plan: 'Free',
    keywords: ['timestamp', 'unix', 'date', 'converter'],
  },
];

export function toolHref(slug: string) {
  return `/tools/${slug}`;
}
